stages:
  build

build:
  stage: build
  script:
    - echo $CI_REGISTRY_PASS |  docker login -u $CI_REGISTRY_USER --password-stdin $CI_DOCKER_REGISTRY
    - docker build -t $CI_DOCKER_REGISTRY/worker:$CI_COMMIT_SHA ./worker
    - docker push $CI_DOCKER_REGISTRY/worker:$CI_COMMIT_SHA



  only:
    - test
