postgres:
  image: postgres:16
  user: saffron
  password: saffron
  db: saffronqueue

redis:
  image: redis:7

api:
  image: mmdbgr/api:1
  replicaCount: 1

worker:
  image: mmdbgr/worker:1
  replicaCount: 1
